"""Seed initial data: medical acts, common medications."""
import aiosqlite
from config import DATABASE_PATH


MEDICAL_ACTS = [
    ("CS", "Consultation spécialisée", "Consultation", 30.00),
    ("C", "Consultation générale", "Consultation", 26.50),
    ("CSO", "Consultation en urgence", "Urgence", 40.00),
    ("ADE", "Acte technique diagnostique", "Acte technique", 55.00),
    ("KC25", "Acte chirurgical KC25", "Chirurgie", 73.13),
    ("KC50", "Acte chirurgical KC50", "Chirurgie", 146.25),
    ("IFD", "Injection intramusculaire", "Injection", 3.70),
    ("ECBU", "ECBU (prélevement)", "Biologie", 15.00),
    ("ECG", "Électrocardiogramme", "Cardio", 14.26),
    ("YYYY", "Radiologie standard", "Imagerie", 25.00),
    ("VT", "Visite à domicile", "Visite", 35.00),
    ("DE", "Dossier entretien / coordination", "Admin", 20.00),
]

MEDICATIONS = [
    # General medications (name, active_ingredient, category, specialty)
    ("Paracétamol 500mg", "Paracétamol", "Antalgique", "general"),
    ("Paracétamol 1000mg", "Paracétamol", "Antalgique", "general"),
    ("Ibuprofène 400mg", "Ibuprofène", "Anti-inflammatoire", "general"),
    ("Amoxicilline 500mg", "Amoxicilline", "Antibiotique", "general"),
    ("Amoxicilline 1g", "Amoxicilline", "Antibiotique", "general"),
    ("Augmentin 875mg", "Amoxicilline/Acide clavulanique", "Antibiotique", "general"),
    ("Azithromycine 250mg", "Azithromycine", "Antibiotique", "general"),
    ("Oméprazole 20mg", "Oméprazole", "IPP", "general"),
    ("Pantoprazole 40mg", "Pantoprazole", "IPP", "general"),
    ("Metformine 500mg", "Metformine", "Antidiabétique", "general"),
    ("Metformine 1000mg", "Metformine", "Antidiabétique", "general"),
    ("Amlodipine 5mg", "Amlodipine", "Antihypertenseur", "general"),
    ("Ramipril 5mg", "Ramipril", "IEC", "general"),
    ("Atorvastatine 10mg", "Atorvastatine", "Statine", "general"),
    ("Doliprane 1000mg", "Paracétamol", "Antalgique", "general"),
    ("Efferalgan 1g", "Paracétamol", "Antalgique", "general"),
    ("Spasfon 40mg", "Phloroglucinol", "Antispasmodique", "general"),
    ("Lexomil 6mg", "Bromazépam", "Anxiolytique", "general"),
    ("Ventoline 100mcg", "Salbutamol", "Bronchodilatateur", "general"),
    ("Levothyrox 50mcg", "Lévothyroxine", "Thyroïde", "general"),
    ("Seretide 25/250", "Salmétérol/Fluticasone", "Bronchodilatateur", "general"),
    ("Prednisolone 20mg", "Prednisolone", "Corticoïde", "general"),
    ("Singulair 10mg", "Montélukast", "Antiasthmatique", "general"),
    ("Xarelto 20mg", "Rivaroxaban", "Anticoagulant", "general"),
    ("Eliquis 5mg", "Apixaban", "Anticoagulant", "general"),
    # Dental medications — commonly prescribed by dentists in Morocco
    ("Amoxicilline 1g", "Amoxicilline", "Antibiotique", "dentiste"),
    ("Augmentin 1g", "Amoxicilline/Acide clavulanique", "Antibiotique", "dentiste"),
    ("Métronidazole 250mg (Flagyl)", "Métronidazole", "Antibiotique", "dentiste"),
    ("Métronidazole 500mg (Flagyl)", "Métronidazole", "Antibiotique", "dentiste"),
    ("Spiramycine 3M UI (Rovamycine)", "Spiramycine", "Antibiotique", "dentiste"),
    ("Spiramycine/Métronidazole (Rodogyl)", "Spiramycine/Métronidazole", "Antibiotique", "dentiste"),
    ("Azithromycine 500mg (Zithromax)", "Azithromycine", "Antibiotique", "dentiste"),
    ("Clindamycine 300mg (Dalacine)", "Clindamycine", "Antibiotique", "dentiste"),
    ("Céfixime 200mg (Oroken)", "Céfixime", "Antibiotique", "dentiste"),
    ("Paracétamol 1000mg (Doliprane)", "Paracétamol", "Antalgique", "dentiste"),
    ("Paracétamol 500mg", "Paracétamol", "Antalgique", "dentiste"),
    ("Ibuprofène 400mg (Brufen)", "Ibuprofène", "Anti-inflammatoire", "dentiste"),
    ("Ibuprofène 600mg", "Ibuprofène", "Anti-inflammatoire", "dentiste"),
    ("Kétoprofène 100mg (Profenid)", "Kétoprofène", "Anti-inflammatoire", "dentiste"),
    ("Diclofénac 50mg (Voltarène)", "Diclofénac", "Anti-inflammatoire", "dentiste"),
    ("Diclofénac 75mg (Voltarène)", "Diclofénac", "Anti-inflammatoire", "dentiste"),
    ("Acide Méfénamique 250mg (Ponstyl)", "Acide Méfénamique", "Anti-inflammatoire", "dentiste"),
    ("Paracétamol/Codéine (Codoliprane)", "Paracétamol/Codéine", "Antalgique", "dentiste"),
    ("Tramadol 50mg", "Tramadol", "Antalgique", "dentiste"),
    ("Prednisolone 20mg (Solupred)", "Prednisolone", "Corticoïde", "dentiste"),
    ("Dexaméthasone 4mg", "Dexaméthasone", "Corticoïde", "dentiste"),
    ("Chlorhexidine 0.12% (Eludril)", "Chlorhexidine", "Bain de bouche", "dentiste"),
    ("Chlorhexidine 0.20% (Paroex)", "Chlorhexidine", "Bain de bouche", "dentiste"),
    ("Hexétidine (Hextril)", "Hexétidine", "Bain de bouche", "dentiste"),
    ("Acide Hyaluronique gel (Hyalugel)", "Acide Hyaluronique", "Topique buccal", "dentiste"),
    ("Miconazole gel buccal (Daktarin)", "Miconazole", "Antifongique", "dentiste"),
    ("Fluconazole 150mg", "Fluconazole", "Antifongique", "dentiste"),
    ("Aciclovir 200mg (Zovirax)", "Aciclovir", "Antiviral", "dentiste"),
    ("Aciclovir crème 5%", "Aciclovir", "Antiviral topique", "dentiste"),
    ("Lidocaïne gel 2% (Dynexan)", "Lidocaïne", "Anesthésique local", "dentiste"),
    ("Oxyde de zinc/eugénol (pansement)", "Oxyde de zinc/Eugénol", "Pansement dentaire", "dentiste"),
    ("Acide Tranexamique 500mg (Exacyl)", "Acide Tranexamique", "Hémostatique", "dentiste"),
]

# (code, categorie, libelle, lettre, cotation, cotation_bis, valeure_lettre, remarques)
NGAP_ACTS = [
    ("C","Consultation","Consultation chez un médecin généraliste ou médecin dentiste.","C",1,0,150,"Une ordonnance avec le motif de consultation ou bien une préscription doit être jointe à la feuille de soins pour prétendre au remboursement."),
    ("V","Consultation","Visite à domicile d'un médecin généraliste, médecin dentiste, lors des jours fériés ou la nuit.","V",1,0,190,"Une ordonnance avec le motif de la visite ou bien une préscription doit être jointe à la feuille de soins pour prétendre au remboursement."),
    ("D626","Orthopédie Dento-faciale","Examen de diagnostic d'ODF (hors examens complémentaires)","D",15,0,17.5,""),
    ("D627","Orthopédie Dento-faciale","Analyse céphalométrique","D",5,0,17.5,""),
    ("D628","Orthopédie Dento-faciale","Scéance de ré-éducation de la déglutition ou phonation (par série de douze séances)","D",5,0,17.5,""),
    ("D629","Orthopédie Dento-faciale","Traitement des dysmorphoses : Semestre","D",90,0,17.5,""),
    ("D630","Orthopédie Dento-faciale","Traitement des dysmorphoses : Plafond","D",540,0,17.5,""),
    ("D631","Orthopédie Dento-faciale","Interruption du traitement de dysmorphoses : Séance de surveillance","D",5,0,17.5,""),
    ("D632","Orthopédie Dento-faciale","Interruption du traitement de dysmorphoses : Première année","D",75,0,17.5,""),
    ("D633","Orthopédie Dento-faciale","Interruption du traitement de dysmorphoses : Deuxième année","D",50,0,17.5,""),
    ("D634","Orthopédie Dento-faciale","Mise en occlusion d'une canine incluse (avant le 18e anniversaire)","D",150,0,17.5,""),
    ("D635","Orthopédie Dento-faciale","Mise en occlusion de deux canines incluses (avant le 18e anniversaire)","D",200,0,17.5,""),
    ("D636","Orthopédie Dento-faciale","Contention après traitement orthodontique : Pemière année","D",75,0,17.5,""),
    ("D637","Orthopédie Dento-faciale","Contention après traitement orthodontique : Deuxième année","D",50,0,17.5,""),
    ("D638","Orthopédie Dento-faciale","Disjonction intrarmaxillaire rapide pour dysmorphose maxillaire en cas d'insuffisance respiratoire confirmée","D",180,0,17.5,""),
    ("D639","Orthopédie Dento-faciale","Orthopédie des malformations consécutives au bec-de-lièvre total ou à la division palatine : forfait annuel, par année","D",200,0,17.5,""),
    ("D640","Orthopédie Dento-faciale","Orthopédie des malformations consécutives au bec-de-lièvre total ou à la division palatine : en période d'attente","D",60,0,17.5,""),
    ("D641","Orthopédie Dento-faciale","Traitement d'orthopédie dento-faciale au delà du seizième anniversaire, préalable à une intervention chirurgicale portant sur les maxillaires, pour une période de six mois non renouvelable","D",90,0,17.5,""),
    ("D700","Soins conservateurs","Curetage et obturation coronaire de cavité simple","D",10,0,17.5,""),
    ("D701","Soins conservateurs","Curetage et obturation coronaire de cavité composée de 2 faces","D",10,0,17.5,""),
    ("D702","Soins conservateurs","Curetage et obturation coronaire de cavité composée de 3 faces et plus","D",15,0,17.5,""),
    ("D703","Soins conservateurs","Pulpotomie ou pulpectomie coronaire avec obturation de la chambre pulpaire","D",7,0,17.5,""),
    ("D704","Soins conservateurs","Traitement endodontique du groupe inciso-canin","D",10,0,17.5,"Une radiographie pré-opératoire et une radiographie post-opératoire sont obligatoires"),
    ("D705","Soins conservateurs","Traitement endodontique du groupe prémolaires","D",15,0,17.5,"Une radiographie pré-opératoire et une radiographie post-opératoire sont obligatoires"),
    ("D706","Soins conservateurs","Traitement endodontique du groupe molaires","D",25,0,17.5,"Une radiographie pré-opératoire et une radiographie post-opératoire sont obligatoires"),
    ("D707","Soins conservateurs","Restauration par matériau inséré en phase plastique avec ancrage radiculaire","D",33,0,17.5,""),
    ("D708","Soins conservateurs","Séance de détartrage complet sus et sous-gingival","D",12,0,17.5,""),
    ("D709","Soins conservateurs","Ligature métallique dans les parodontopathies","D",8,0,17.5,""),
    ("D710","Soins conservateurs","Attelle métallique dans les parodontopathies","D",40,0,17.5,""),
    ("D711","Soins conservateurs","Prothèse attelle de contention quel que soit le nombre de dents ou de crochets","D",70,0,17.5,""),
    ("D712","Soins conservateurs","Scellement prophylactique des puits, sillons et fissures, par dent","D",8,0,17.5,""),
    ("D713","Soins chirurgicaux","Extraction d'une dent permanente","D",10,0,17.5,""),
    ("D714","Soins chirurgicaux","Extraction de chacune des suivantes au cours de la même séance","D",5,0,17.5,""),
    ("D715","Soins chirurgicaux","Extraction d'une dent lactéale, quelle que soit la technique","D",8,0,17.5,""),
    ("D716","Soins chirurgicaux","Extraction de chacune des dents suivantes au cours de la même séance","D",4,0,17.5,""),
    ("D717","Soins chirurgicaux","Extraction d'une dent par alvéolectomie","D",10,0,17.5,""),
    ("D718","Soins chirurgicaux","Anesthésie générale pour une à douze extractions","D",25,0,17.5,""),
    ("D719","Soins chirurgicaux","Anesthésie générale pour treize extractions et plus","D",30,0,17.5,""),
    ("D720","Soins chirurgicaux","Extraction de la première dent de sagesse incluse","D",40,0,17.5,"Une radiographie pré-opératoire est obligatoire"),
    ("D721","Soins chirurgicaux","Extraction des dents de sagesse incluses suivantes au cours de la même séance","D",20,0,17.5,"Une radiographie pré-opératoire est obligatoire"),
    ("D722","Soins chirurgicaux","Anesthésie générale pour une dent incluse","D",25,25,17.5,"Une radiographie pré-opératoire est obligatoire"),
    ("D723","Soins chirurgicaux","Anesthésie générale pour deux dents incluses ou plus","D",40,40,17.5,"Une radiographie pré-opératoire est obligatoire"),
    ("D724","Soins chirurgicaux","Germectomie pour une autre dent que la dent de sagesse","D",20,0,17.5,"Une radiographie pré-opératoire est obligatoire"),
    ("D725","Soins chirurgicaux","Extraction d'une dent incluse ou enclavée","D",40,0,17.5,"Une radiographie pré-opératoire est obligatoire"),
    ("D726","Soins chirurgicaux","Extraction d'une canine incluse","D",50,30,17.5,"Une radiographie pré-opératoire est obligatoire"),
    ("D727","Soins chirurgicaux","Extraction d'une odontoïde ou d'une dent surnuméraire incluse ou enclavée","D",40,0,17.5,"Une radiographie pré-opératoire est obligatoire"),
    ("D728","Soins chirurgicaux","Extraction d'une dent en désinclusion non enclavée, dont la couronne est sous-muqueuse","D",20,0,17.5,"Une radiographie pré-opératoire est obligatoire"),
    ("D729","Soins chirurgicaux","Extraction d'une dent en désinclusion dont la couronne est sous muqueuse en position palatine ou linguale","D",30,30,17.5,"Une radiographie pré-opératoire est obligatoire"),
    ("D730","Soins chirurgicaux","Extraction d'une dent ectopique et incluse (coroné, gonion, branche montante, bord basilaire de la branche et du menton, sinus)","D",30,30,17.5,"Une radiographie pré-opératoire est obligatoire"),
    ("D731","Soins chirurgicaux","Extraction chirurgicale d'une dent permanente incluse, traitement radiculaire éventuel, réimplantation, contention : D'une dent","D",100,30,17.5,"Une radiographie pré-opératoire est obligatoire"),
    ("D732","Soins chirurgicaux","Extraction chirurgicale d'une dent permanente incluse, traitement radiculaire éventuel, réimplantation, contention : De deux dents","D",150,40,17.5,"Une radiographie pré-opératoire est obligatoire"),
    ("D733","Soins chirurgicaux","Trépanation du sinus maxillaire, par voie vestibulaire, pour recherche d'une racine dentaire","D",40,0,17.5,""),
    ("D734","Soins chirurgicaux","Dégagement chirurgical de la couronne d'une dent permanente incluse","D",30,0,17.5,""),
    ("D735","Soins chirurgicaux","Régularisation d'une crête alvéolaire avec suture gingivale : Localisée, et dans une autre séance que celle de l'extraction","D",5,0,17.5,""),
    ("D736","Soins chirurgicaux","Régularisation d'une crête alvéolaire avec suture gingivale : Etendue à la crête d'un hémimaxillaire ou de canine à canine","D",15,0,17.5,""),
    ("D737","Soins chirurgicaux","Régularisation d'une crête alvéolaire avec suture gingivale : Etendue à la totalité de la crête","D",30,0,17.5,""),
    ("D738","Soins chirurgicaux","Curetage périapical avec ou sans résection apicale (radiographie obligatoire, traitement et obturation du canal non compris)","D",15,0,17.5,"Une radiographie pré-opératoire est obligatoire"),
    ("D739","Soins chirurgicaux","Exérèse chirurgicale d'un kyste de petit volume par voie alvéolaire élargie","D",15,0,17.5,"Une radiographie pré-opératoire est obligatoire"),
    ("D740","Soins chirurgicaux","Exérèse chirurgicale d'un kyste étendu aux apex de deux dents et nécessitant une trépanation osseuse","D",30,0,17.5,"Une radiographie pré-opératoire est obligatoire"),
    ("D741","Soins chirurgicaux","Exérèse chirurgicale d'un kyste étendu à un segment important du maxillaire","D",50,30,17.5,"Une radiographie pré-opératoire est obligatoire"),
    ("D742","Soins chirurgicaux","Gingivectomie partielle","D",5,0,17.5,""),
    ("D743","Soins chirurgicaux","Gingivectomie étendue à un sextant : (de canine à canine, de prémolaire à dent de sagesse)","D",20,0,17.5,""),
    ("D744","Soins chirurgicaux","Traitement d'une hémorragie post-opératoire dans une séance autre que celle de l'intervention","D",10,0,17.5,""),
    ("D745","Soins chirurgicaux","Désinsertion musculaire d'un vestibule supérieur ou inférieur","D",40,20,17.5,""),
    ("D746","Soins chirurgicaux","Désinsertion musculaire du plancher de la bouche avec section des mylohyoïdiens","D",60,20,17.5,""),
    ("D747","Soins chirurgicaux","Approfondissement d'un vestibule par greffe cutanée","D",40,20,17.5,""),
    ("D748","Prothèse dentaire","Couronnes en acier ou en nickel chromé.","D",40,0,12.5,""),
    ("D749","Prothèse dentaire","Couronnes en or jaune ou en métaux précieux","D",60,0,12.5,""),
    ("D750","Prothèse dentaire","Couronnes coulées en acier ou en nickel chromé","D",50,0,12.5,""),
    ("D751","Prothèse dentaire","Couronnes coulées en or jaune ou métaux précieux","D",80,0,12.5,""),
    ("D752","Prothèse dentaire","Couronnes à incrustation vestibulaire ou couronnes veneer en acier","D",75,0,12.5,""),
    ("D753","Prothèse dentaire","Couronnes à incrustation vestibulaire en or jaune ou en métaux précieux","D",120,0,12.5,""),
    ("D754","Prothèse dentaire","Couronnes céramo-métal","D",180,0,12.5,""),
    ("D755","Prothèse dentaire","Couronnes jacket céramo-métal","D",180,0,12.5,""),
    ("D756","Prothèse dentaire","Couronnes jacket cuite","D",40,0,12.5,""),
    ("D757","Prothèse dentaire","Chaque élément du bridge sera compté comme couronne unitaire de même nature","D",0,0,12.5,""),
    ("D758","Prothèse dentaire","Les inlay-cores en or jaune ou métal précieux sur dents uniradiculaires","D",80,0,12.5,""),
    ("D759","Prothèse dentaire","Les inlay-cores en or jaune ou métal précieux sur dents pluriradiculaires","D",100,0,12.5,""),
    ("D760","Prothèse dentaire","Les dents à pivots esthétiques en or jaune ou métaux précieux","D",150,0,12.5,""),
    ("D761","Prothèse dentaire","Appareil sur plaque base en matière plastique d'un édentement d'une à trois dents","D",40,0,12.5,""),
    ("D762","Prothèse dentaire","Appareil sur plaque base en matière plastique d'un édentement de quatre dents","D",45,0,12.5,""),
    ("D763","Prothèse dentaire","Appareil sur plaque base en matière plastique d'un édentement de cinq dents","D",50,0,12.5,""),
    ("D764","Prothèse dentaire","Appareil sur plaque base en matière plastique d'un édentement de six dents","D",55,0,12.5,""),
    ("D765","Prothèse dentaire","Appareil sur plaque base en matière plastique d'un édentement de sept dents","D",60,0,12.5,""),
    ("D766","Prothèse dentaire","Appareil sur plaque base en matière plastique d'un édentement de huit dents","D",65,0,12.5,""),
    ("D767","Prothèse dentaire","Appareil sur plaque base en matière plastique d'un édentement de neuf dents","D",70,0,12.5,""),
    ("D768","Prothèse dentaire","Appareil sur plaque base en matière plastique d'un édentement de dix dents","D",75,0,12.5,""),
    ("D769","Prothèse dentaire","Appareil sur plaque base en matière plastique d'un édentement de onze dents","D",80,0,12.5,""),
    ("D770","Prothèse dentaire","Appareil sur plaque base en matière plastique d'un édentement de douze dents","D",85,0,12.5,""),
    ("D771","Prothèse dentaire","Appareil sur plaque base en matière plastique d'un édentement de treize dents","D",90,0,12.5,""),
    ("D772","Prothèse dentaire","Appareil sur plaque base en matière plastique d'un édentement de quatorze dents","D",95,0,12.5,""),
    ("D773","Prothèse dentaire","Prothèse adjointe totale du maxillaire supérieur","D",120,0,12.5,""),
    ("D774","Prothèse dentaire","Prothèse adjointe totale du maxillaire inférieur","D",120,0,12.5,""),
    ("D775","Prothèse dentaire","Supplément pour plaque base métallique","D",120,0,12.5,""),
    ("D776","Prothèse dentaire","Supplément pour dent prothétique contreplaquée sur plaque base en matière plastique","D",10,0,12.5,""),
    ("D777","Prothèse dentaire","Supplément pour dent prothétique contreplaquée ou massive sur plaque base métallique","D",15,0,12.5,""),
    ("D778","Prothèse dentaire","Réparation de fractures de la plaque base en matière plastique","D",10,0,12.5,""),
    ("D779","Prothèse dentaire","Réparation de fractures de la plaque base métallique, non compris, s'il y a lieu, le remontage des dents sur matière plastique","D",15,0,12.5,""),
    ("D780","Prothèse dentaire","Dents ou crochets ajoutés ou remplacés sur appareil en matière plastique, ou à chassis métallique (premier élément)","D",10,0,12.5,""),
    ("D781","Prothèse dentaire","Dents ou crochets ajoutés ou remplacés sur appareil en matière plastique, ou à chassis métallique (les suivants, sur le même appareil)","D",5,0,12.5,""),
    ("D782","Prothèse dentaire","Dents contreplaquées ou massives et crochets, soudés, ajoutés ou remplacés sur appareil métallique (par élément)","D",20,0,12.5,""),
    ("D783","Prothèse dentaire","Dents ou crochets remontés sur matière plastique, après réparation de la plaque base métallique (par élément)","D",3,0,12.5,""),
    ("D784","Prothèse dentaire","Remplacement de facette","D",8,0,12.5,""),
    ("D785","Prothèse dentaire","Supplément d'attachement de PAP à la cotation de la plaque métallique","D",40,0,12.5,""),
    ("D800","Prothèse restauratrice maxillo-faciale","Appareillage par obturateur pour perforation palatine de moins de 1 cm","D",25,0,12.5,""),
    ("D801","Prothèse restauratrice maxillo-faciale","Appareillage par obturateur pour perte de substance du maxillaire ou de la mandibule s'il s'agit d'une prothèse partielle","D",40,0,12.5,""),
    ("D802","Prothèse restauratrice maxillo-faciale","Appareillage par obturateur pour perte de substance du maxillaire ou de la mandibule s'il s'agit d'une prothèse complète","D",80,0,12.5,""),
    ("D803","Prothèse restauratrice maxillo-faciale","Appareillage par obturateur pour perte de substance vélopalatine","D",100,0,12.5,""),
    ("D804","Prothèse restauratrice maxillo-faciale","Prothèse à étages pour résection élargie du maxillaire supérieur (prothèse dentaire non comprise)","D",150,0,12.5,""),
    ("D805","Prothèse restauratrice maxillo-faciale","Chapes de recouvrement (support de prothèse vélopalatine), par élément","D",25,0,12.5,""),
    ("D806","Prothèse restauratrice maxillo-faciale","Prothèse de recouvrement pour correction de l'articulé","D",60,0,12.5,""),
    ("D807","Prothèse restauratrice maxillo-faciale","Appareillage de contention ou de réduction pré-opératoire et post-opératoire du maxillaire ou de la mandibule (résection chirurgicale ou greffe)","D",130,0,12.5,""),
    ("D808","Prothèse restauratrice maxillo-faciale","Appareillage par mobilisateur du maxillaire inférieur (quel que soit le modèle)","D",80,0,12.5,""),
    ("D809","Prothèse restauratrice maxillo-faciale","Appareillage par appui péricrânien","D",60,0,12.5,""),
    ("D810","Prothèse restauratrice maxillo-faciale","Appareillage par appareil guide : sur une arcade","D",40,0,12.5,""),
    ("D811","Prothèse restauratrice maxillo-faciale","Appareillage par appareil guide : sur deux arcades","D",80,0,12.5,""),
    ("D812","Prothèse restauratrice maxillo-faciale","Appareillage de distension des cicatrices vicieuses","D",80,0,12.5,""),
    ("D813","Prothèse restauratrice maxillo-faciale","Appareil porte-radium ou appareil de protection des maxillaires pour radiations ionisantes","D",80,0,12.5,""),
    ("D814","Prothèse restauratrice maxillo-faciale","Appareillage de redressement nasal avec point d'appui dento-maxillaire ou péricrânien","D",140,0,12.5,""),
    ("D815","Prothèse restauratrice maxillo-faciale","Moulage facial","D",20,0,12.5,""),
    ("D816","Prothèse restauratrice maxillo-faciale","Prothèse plastique faciale (par exemple, du pavillon de l'oreille ou du nez); prise en charge, après accord préalable, suivant devis du praticien traitant.","D",0,0,0,""),
    ("D900","Prothèse dentaire","Couronne céramo-céramique","D",200,0,12.5,""),
    ("D901","Prothèse dentaire","Inlay onlay céramique","D",180,0,12.5,""),
    ("D902","Prothèse dentaire","Facette céramique","D",180,0,12.5,""),
    ("D903","Prothèse dentaire","Dent à tenon céramo-métallique","D",200,0,12.5,""),
    ("D904","Prothèse dentaire","Dent provisoire en résine (par élément)","D",10,0,12.5,""),
    ("D905","Soins conservateurs","Dépose d'un ancrage radiculaire, coronaire, unitaire ou plural","D",20,0,17.5,""),
    ("D906","Soins chirurgicaux","Extraction d'une dent ankylosée","D",40,0,17.5,""),
    ("D907","Prothèse dentaire","Mainteneur d'espace fixe unilatéral","D",20,0,12.5,""),
    ("D908","Prothèse dentaire","Mainteneur d'espace fixe bilatéral","D",40,0,12.5,""),
    ("D909","Prothèse dentaire","Prothèse dentaire amovible pédiatrique","D",40,0,12.5,""),
    ("D910","Soins conservateurs","Eclaircissement d'une dent dépulpée","D",25,0,17.5,""),
    ("D911","Soins conservateurs","Reminéralisation une à deux dents","D",8,0,17.5,""),
    ("D912","Soins conservateurs","Reminéralisation de 2 à 6 dents","D",12,0,17.5,""),
    ("D913","Soins conservateurs","Reminéralisation par arcade","D",15,0,17.5,""),
    ("D914","Soins conservateurs","Etanchéification par dent","D",8,0,17.5,""),
    ("T142","Radiographie de la tête","Incidences fondamentales : face, profil, projection sus-orbitaire des rochers, par incidence","Z",6,0,10,""),
    ("T143","Radiographie de la tête","Incidences spéciales : projections verticales de base, incidences obliques, opacification des sinus, par incidence","Z",10,0,10,""),
    ("T144","Radiographie de la tête","Recherche d'un corps étranger oculaire par radiographie multiples, l'examen","Z",15,0,10,""),
    ("T145","Radiographie de la tête","Maxillaire défilé, os propres du nez, articulation temporo-maxillaire","Z",8,0,10,""),
    ("T146","Radiographie de la tête","Examen radiologique du crâne, massif facial, sinus, une incidence","Z",15,0,10,""),
    ("T147","Radiographie de la tête","Examen radiologique du crâne, massif facial, sinus, deux ou trois incidences","Z",18,0,10,""),
    ("T148","Radiographie de la tête","Examen radiologique du crâne, massif facial, sinus, quatre incidences et plus","Z",26,0,10,""),
    ("T149","Radiographie de la tête","Examen radiographique des os propres du nez, y compris la cloison, incluant l'ensemble des incidences nécessaires","Z",17,0,10,""),
    ("T150","Radiographie de la tête","Examen radiographique des articulations temporo-maxillaires","Z",19,0,10,""),
    ("T151","Radiographie de la tête","Examen radiographique panoramique de la totalité du système maxillaire et du système dentaire (technique tomographique)","Z",16,0,10,""),
    ("T152","Radiographie de la tête","Examen radiographique du crâne : incidences de Schuller (les deux côtés), non cumulable avec la radiographie du crâne","Z",15,0,10,""),
    ("T153","Radiographie de la tête","Téléradiographie du crâne à trois mètres (diagnostique orthodontique), par incidence","Z",10,0,10,""),
    ("T154","Radiographie de la tête","Téléradiographie du crâne à 4 mètres (diagnostic orthodontique), une incidence","Z",15,0,10,""),
    ("T155","Radiographie de la tête","Téléradiographie du crâne à 4 mètres (diagnostic orthodontique), deux incidences et plus","Z",20,0,10,""),
    ("T156","Radiographie de la tête","Premier cliché d'un examen radiographique intra-buccal rétroalvéolaire, par dent ou groupe de deux ou trois dents contiguës, au cours d'une même séance de diagnostic ou de traitement","Z",4,0,10,""),
    ("T157","Radiographie de la tête","Deuxième cliché et suivants d'un examen radiographique intrabuccal rétroalvéolaire par dent ou groupe de deux ou trois dents contiguës, au cours d'une même séance de diagnostic ou de traitement","Z",1,0,10,""),
    ("T158","Radiographie de la tête","Bilan complet en téléradiographie intrabuccale (status), au cours d'une même séance, quel que soit le nombre de clichés rétroalvéolaires ou rétrocoronaires","Z",56,0,10,""),
    ("T159","Radiographie de la tête","Examen radiographique intra-buccal à images numérisées par capteur, par dent ou groupe de deux ou trois dents contiguës, au cours d'une même séance de diagnostic ou de traitement","Z",6,0,10,"Pour donner lieu à remboursement, l'examen ci-dessus doit être matérialisé par au moins un support papier indiquant la date, l'identification du patient et celle de la dent ou des dents concernées."),
]


async def seed_db():
    """Insert initial data only if tables are empty."""
    db = await aiosqlite.connect(DATABASE_PATH)

    # Medical acts
    cursor = await db.execute("SELECT COUNT(*) FROM medical_acts")
    count = (await cursor.fetchone())[0]
    if count == 0:
        await db.executemany(
            "INSERT INTO medical_acts (code, name, category, base_price) VALUES (?, ?, ?, ?)",
            MEDICAL_ACTS,
        )

    # Medications
    cursor = await db.execute("SELECT COUNT(*) FROM medications")
    count = (await cursor.fetchone())[0]
    if count == 0:
        await db.executemany(
            "INSERT INTO medications (name, active_ingredient, category, specialty) VALUES (?, ?, ?, ?)",
            MEDICATIONS,
        )
    else:
        # Add dental medications if missing
        cursor = await db.execute("SELECT COUNT(*) FROM medications WHERE specialty = 'dentiste'")
        dental_count = (await cursor.fetchone())[0]
        if dental_count == 0:
            dental_meds = [m for m in MEDICATIONS if m[3] == "dentiste"]
            await db.executemany(
                "INSERT INTO medications (name, active_ingredient, category, specialty) VALUES (?, ?, ?, ?)",
                dental_meds,
            )
            # Tag existing meds as general
            await db.execute("UPDATE medications SET specialty = 'general' WHERE specialty IS NULL")

    # NGAP acts
    cursor = await db.execute("SELECT COUNT(*) FROM ngap_acts")
    if (await cursor.fetchone())[0] == 0:
        await db.executemany(
            "INSERT INTO ngap_acts (code, categorie, libelle, lettre, cotation, cotation_bis, valeure_lettre, remarques) VALUES (?,?,?,?,?,?,?,?)",
            NGAP_ACTS,
        )

    await db.commit()
    await db.close()
